spring:
  application:
    name: OutOfMemory
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/outofmemory_test?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: li1259535860
  elasticsearch:
    rest:
      uris: http://101.42.251.254:9200
server:
  port: 8000

logging:
  level:
    root: debug
  file:
    name: outofmemory.log
//    developer.outofmemory.dao: debug

mybatis-plus:
  mapper-locations: classpath:**/*.xml

