spring:
  application:
    name: OutOfMemory
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/outofmemory_test?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
  elasticsearch:
    rest:
      uris: http://localhost:9200
server:
  port: 8000

logging:
  level:
    root: debug
  file:
    name: outofmemory.log
//    developer.outofmemory.dao: debug

mybatis-plus:
  mapper-locations: classpath:**/*.xml


