spring:
  application:
    name: OutOfMemory
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.42.251.254:3306/outofmemory?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
server:
  port: 8000

logging:
  level:
    root: warn
  file:
    name: outofmemory.log
//    developer.outofmemory.dao: debug

mybatis-plus:
  mapper-locations: classpath:**/*.xml

